export const collection = {
brand:"Versace",
brandFa:"ورساچه",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
description:"Discover the latest Versace luxury accessories collection.",
descriptionFa:"جدیدترین کالکشن اکسسوری‌های لوکس ورساچه را مشاهده کنید."
};
export const products = [
{
id:"versace-01",
name:"Ring",
nameFa:"رینگ",
oldPrice:"$8,200",
newPrice:"$7,790",
image:"../../../../../src/assets/images/acs-images/Versace/bracelet1.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/bracelet1.jpg"],
url:"#",
description:"Elegant bracelet crafted with premium materials.",
descriptionFa:"دستبندی ظریف که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-02",
name:"Neverfull MM",
nameFa:"نِوِرفول ام‌ام",
oldPrice:"$2,350",
newPrice:"$2,090",
image:"../../../../../src/assets/images/acs-images/Versace/bracelet2.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/bracelet2.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-03",
name:"Speedy Bandoulière 25",
nameFa:"اسپیدی باندولیر ۲۵",
oldPrice:"$2,450",
newPrice:"$2,190",
image:"../../../../../src/assets/images/acs-images/Versace/bracelet3.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/bracelet3.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-04",
name:"Alma BB",
nameFa:"آلما بی‌بی",
oldPrice:"$2,180",
newPrice:"$1,950",
image:"../../../../../src/assets/images/acs-images/Versace/bracelet4.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/bracelet4.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-05",
name:"Twist MM",
nameFa:"توئیست ام‌ام",
oldPrice:"$5,450",
newPrice:"$4,990",
image:"../../../../../src/assets/images/acs-images/Versace/necklace1.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/necklace1.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-06",
name:"Pochette Métis",
nameFa:"پوشت متیس",
oldPrice:"$3,250",
newPrice:"$2,990",
image:"../../../../../src/assets/images/acs-images/Versace/necklace2.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/necklace2.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-07",
name:"Loop Hobo",
nameFa:"لوپ هوبو",
oldPrice:"$3,150",
newPrice:"$2,850",
image:"../../../../../src/assets/images/acs-images/Versace/necklace3.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/necklace3.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-08",
name:"CarryAll PM",
nameFa:"کری‌اُل پی‌ام",
oldPrice:"$3,450",
newPrice:"$3,090",
image:"../../../../../src/assets/images/acs-images/Versace/necklace4.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/necklace4.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-09",
name:"Boulogne",
nameFa:"بولون",
oldPrice:"$2,790",
newPrice:"$2,490",
image:"../../../../../src/assets/images/acs-images/Versace/ring1.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/ring1.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-10",
name:"Diane",
nameFa:"دایان",
oldPrice:"$2,950",
newPrice:"$2,690",
image:"../../../../../src/assets/images/acs-images/Versace/ring2.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/ring2.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-11",
name:"OnTheGo MM",
nameFa:"آن‌دِگو ام‌ام",
oldPrice:"$3,850",
newPrice:"$3,490",
image:"../../../../../src/assets/images/acs-images/Versace/ring3.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/ring3.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-12",
name:"Bella Tote",
nameFa:"بلا توت",
oldPrice:"$4,150",
newPrice:"$3,790",
image:"../../../../../src/assets/images/acs-images/Versace/ring4.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/ring4.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-13",
name:"Nano Speedy",
nameFa:"نانو اسپیدی",
oldPrice:"$1,980",
newPrice:"$1,790",
image:"../../../../../src/assets/images/acs-images/Versace/glasses1.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/glasses1.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-14",
name:"Wallet On Chain Ivy",
nameFa:"والت آن چین آیوی",
oldPrice:"$2,050",
newPrice:"$1,850",
image:"../../../../../src/assets/images/acs-images/Versace/glasses2.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/glasses2.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-15",
name:"Félicie Pochette",
nameFa:"فِلیسی پوشت",
oldPrice:"$1,850",
newPrice:"$1,650",
image:"../../../../../src/assets/images/acs-images/Versace/glasses3.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/glasses3.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"versace-16",
name:"Mini Bumbag",
nameFa:"مینی بام‌بگ",
oldPrice:"$2,390",
newPrice:"$2,090",
image:"../../../../../src/assets/images/acs-images/Versace/glasses4.jpg",
images:["../../../../../src/assets/images/acs-images/Versace/glasses4.jpg"],
url:"#",
description:"Elegant accessory crafted with premium materials.",
descriptionFa:"اکسسوری ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
}
];