export const collection = {
brand:"Louis Vuitton",
brandFa:"لویی ویتون",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
description:"Discover the latest Louis Vuitton luxury accessories collection.",
descriptionFa:"جدیدترین کالکشن اکسسوری‌های لوکس لویی ویتون را مشاهده کنید."
};

export const products = [
{
id:"louis-vuitton-01",
brand:"louis-vuitton",
name:"Ring",
nameFa:"رینگ",
oldPrice:"$8,200",
newPrice:"$7,790",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton1.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton1.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=1",
description:"Elegant Louis Vuitton ring crafted with premium materials and timeless design.",
descriptionFa:"رینگ ظریف لویی ویتون که با استفاده از مواد باکیفیت و طراحی ماندگار ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"louis-vuitton-02",
brand:"louis-vuitton",
name:"Neverfull MM",
nameFa:"نِوِرفول ام‌ام",
oldPrice:"$2,350",
newPrice:"$2,090",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton2.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton2.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=2",
description:"Luxury Neverfull MM bag with iconic Louis Vuitton craftsmanship.",
descriptionFa:"کیف لوکس نِوِرفول ام‌ام با هنر و ظرافت نمادین لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown","black"],
colorNames:["Brown","Black"],
colorNamesFa:["قهوه‌ای","مشکی"],
sizes:["MM"],
sizesFa:["MM"],
material:"Canvas",
materialFa:"بوم"
},
{
id:"louis-vuitton-03",
brand:"louis-vuitton",
name:"Speedy Bandoulière 25",
nameFa:"اسپیدی باندولیِر ۲۵",
oldPrice:"$2,450",
newPrice:"$2,190",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton3.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton3.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=3",
description:"Classic Speedy Bandoulière 25 handbag with elegant finish.",
descriptionFa:"کیف کلاسیک اسپیدی باندولیِر ۲۵ با طراحی ظریف و پرداختی زیبا.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown"],
colorNames:["Brown"],
colorNamesFa:["قهوه‌ای"],
sizes:["25"],
sizesFa:["۲۵"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-04",
brand:"louis-vuitton",
name:"Alma BB",
nameFa:"آلما بی‌بی",
oldPrice:"$2,180",
newPrice:"$1,950",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton4.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton4.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=4",
description:"Elegant Alma BB handbag with Louis Vuitton signature craftsmanship.",
descriptionFa:"کیف ظریف آلما بی‌بی با هنر و طراحی شاخص لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black","brown"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["BB"],
sizesFa:["BB"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-05",
brand:"louis-vuitton",
name:"Twist MM",
nameFa:"توئیست ام‌ام",
oldPrice:"$5,450",
newPrice:"$4,990",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton5.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton5.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=5",
description:"Modern Twist MM bag designed for luxury and everyday elegance.",
descriptionFa:"کیف مدرن توئیست ام‌ام با طراحی لوکس و مناسب استفاده روزمره.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black"],
colorNames:["Black"],
colorNamesFa:["مشکی"],
sizes:["MM"],
sizesFa:["MM"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-06",
brand:"louis-vuitton",
name:"Pochette Métis",
nameFa:"پوشت متیس",
oldPrice:"$3,250",
newPrice:"$2,990",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton6.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton6.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=6",
description:"Iconic Pochette Métis crafted with premium Louis Vuitton materials.",
descriptionFa:"پوشت متیس نمادین که با مواد باکیفیت لویی ویتون ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown"],
colorNames:["Brown"],
colorNamesFa:["قهوه‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Canvas",
materialFa:"بوم"
},
{
id:"louis-vuitton-07",
brand:"louis-vuitton",
name:"Loop Hobo",
nameFa:"لوپ هوبو",
oldPrice:"$3,150",
newPrice:"$2,850",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton7.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton7.jpg",

],
url:"../pdp/pdp.html?brand=louis-vuitton&id=7",
description:"Luxury Loop Hobo bag with elegant Louis Vuitton design.",
descriptionFa:"کیف لوکس لوپ هوبو با طراحی ظریف لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black","brown"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-08",
brand:"louis-vuitton",
name:"CarryAll PM",
nameFa:"کری‌اُل پی‌ام",
oldPrice:"$3,450",
newPrice:"$3,090",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton8.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton8.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=8",
description:"CarryAll PM handbag with premium craftsmanship and timeless style.",
descriptionFa:"کیف کری‌اُل پی‌ام با ساخت باکیفیت و طراحی ماندگار.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown"],
colorNames:["Brown"],
colorNamesFa:["قهوه‌ای"],
sizes:["PM"],
sizesFa:["PM"],
material:"Canvas",
materialFa:"بوم"
},
{
id:"louis-vuitton-09",
brand:"louis-vuitton",
name:"Boulogne",
nameFa:"بولونی",
oldPrice:"$2,790",
newPrice:"$2,490",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton9.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton9.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=9",
description:"Elegant Boulogne shoulder bag with iconic Louis Vuitton details.",
descriptionFa:"کیف دوشی ظریف بولونی با جزئیات نمادین لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black"],
colorNames:["Black"],
colorNamesFa:["مشکی"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-10",
brand:"louis-vuitton",
name:"Diane",
nameFa:"دایان",
oldPrice:"$2,950",
newPrice:"$2,690",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton10.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton10.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=10",
description:"Classic Diane handbag combining elegance and practicality.",
descriptionFa:"کیف کلاسیک دایان که ظرافت و کاربردی بودن را در کنار هم قرار می‌دهد.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown"],
colorNames:["Brown"],
colorNamesFa:["قهوه‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-11",
brand:"louis-vuitton",
name:"OnTheGo MM",
nameFa:"آن‌دِ‌گو ام‌ام",
oldPrice:"$3,850",
newPrice:"$3,490",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton11.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton11.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=11",
description:"Spacious OnTheGo MM tote designed for everyday luxury.",
descriptionFa:"کیف بزرگ آن‌دِ‌گو ام‌ام با طراحی لوکس برای استفاده روزمره.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown","cream"],
colorNames:["Brown","Cream"],
colorNamesFa:["قهوه‌ای","کرم"],
sizes:["MM"],
sizesFa:["MM"],
material:"Canvas",
materialFa:"بوم"
},
{
id:"louis-vuitton-12",
brand:"louis-vuitton",
name:"Bella Tote",
nameFa:"بلا توت",
oldPrice:"$4,150",
newPrice:"$3,790",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton12.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton12.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=12",
description:"Elegant Bella Tote crafted with luxurious Louis Vuitton materials.",
descriptionFa:"کیف بلا توت ظریف که با مواد لوکس لویی ویتون ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black","cream"],
colorNames:["Black","Cream"],
colorNamesFa:["مشکی","کرم"],
sizes:["Large"],
sizesFa:["بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-13",
brand:"louis-vuitton",
name:"Nano Speedy",
nameFa:"نانو اسپیدی",
oldPrice:"$1,980",
newPrice:"$1,790",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton13.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton13.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=13",
description:"Compact Nano Speedy handbag with timeless Louis Vuitton elegance.",
descriptionFa:"کیف کوچک نانو اسپیدی با ظرافت ماندگار لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown"],
colorNames:["Brown"],
colorNamesFa:["قهوه‌ای"],
sizes:["Nano"],
sizesFa:["نانو"],
material:"Canvas",
materialFa:"بوم"
},
{
id:"louis-vuitton-14",
brand:"louis-vuitton",
name:"Wallet On Chain Ivy",
nameFa:"والت آن چِین آیوی",
oldPrice:"$2,050",
newPrice:"$1,850",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton14.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton14.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=14",
description:"Elegant Wallet On Chain Ivy with signature Louis Vuitton style.",
descriptionFa:"والت آن چِین آیوی ظریف با سبک شاخص لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black","brown"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small"],
sizesFa:["کوچک"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-15",
brand:"louis-vuitton",
name:"Félicie Pochette",
nameFa:"فلیسی پوشت",
oldPrice:"$1,850",
newPrice:"$1,650",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton15.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton15.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=15",
description:"Luxury Félicie Pochette designed for elegant everyday use.",
descriptionFa:"فلیسی پوشت لوکس با طراحی ظریف برای استفاده روزمره.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown","cream"],
colorNames:["Brown","Cream"],
colorNamesFa:["قهوه‌ای","کرم"],
sizes:["Small"],
sizesFa:["کوچک"],
material:"Canvas",
materialFa:"بوم"
},
{
id:"louis-vuitton-16",
brand:"louis-vuitton",
name:"Mini Bumbag",
nameFa:"مینی بام‌بگ",
oldPrice:"$2,390",
newPrice:"$2,090",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton16.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton16.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=16",
description:"Fashionable Mini Bumbag with premium Louis Vuitton craftsmanship.",
descriptionFa:"مینی بام‌بگ شیک با ساخت باکیفیت لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black"],
colorNames:["Black"],
colorNamesFa:["مشکی"],
sizes:["Mini"],
sizesFa:["مینی"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-17",
brand:"louis-vuitton",
name:"Side Trunk MM",
nameFa:"ساید ترانک ام‌ام",
oldPrice:"$5,990",
newPrice:"$5,390",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton17.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton17.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=17",
description:"Exclusive Side Trunk MM combining heritage and modern luxury.",
descriptionFa:"ساید ترانک ام‌ام منحصربه‌فرد که میراث برند و لوکس مدرن را ترکیب می‌کند.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown"],
colorNames:["Brown"],
colorNamesFa:["قهوه‌ای"],
sizes:["MM"],
sizesFa:["MM"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-18",
brand:"louis-vuitton",
name:"GO-14 MM",
nameFa:"گو-۱۴ ام‌ام",
oldPrice:"$7,200",
newPrice:"$6,690",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton18.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton18.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=18",
description:"Luxury GO-14 MM handbag crafted with exceptional attention to detail.",
descriptionFa:"کیف لوکس گو-۱۴ ام‌ام با توجه ویژه به جزئیات ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black","gold"],
colorNames:["Black","Gold"],
colorNamesFa:["مشکی","طلایی"],
sizes:["MM"],
sizesFa:["MM"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-19",
brand:"louis-vuitton",
name:"Liv Pochette",
nameFa:"لیو پوشت",
oldPrice:"$2,250",
newPrice:"$1,990",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton19.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton19.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=19",
description:"Elegant Liv Pochette with iconic Louis Vuitton craftsmanship.",
descriptionFa:"لیو پوشت ظریف با هنر و ساخت نمادین لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown"],
colorNames:["Brown"],
colorNamesFa:["قهوه‌ای"],
sizes:["Small"],
sizesFa:["کوچک"],
material:"Canvas",
materialFa:"بوم"
},
{
id:"louis-vuitton-20",
brand:"louis-vuitton",
name:"Dauphine MM",
nameFa:"دافین ام‌ام",
oldPrice:"$4,250",
newPrice:"$3,890",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton20.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton20.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=20",
description:"Classic Dauphine MM handbag designed with timeless elegance.",
descriptionFa:"کیف کلاسیک دافین ام‌ام با طراحی ظریف و ماندگار.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black","brown"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["MM"],
sizesFa:["MM"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-21",
brand:"louis-vuitton",
name:"Lockme Ever MM",
nameFa:"لاک‌می اِوِر ام‌ام",
oldPrice:"$3,850",
newPrice:"$3,450",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton21.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton21.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=21",
description:"Elegant Lockme Ever MM handbag for everyday luxury.",
descriptionFa:"کیف ظریف لاک‌می اِوِر ام‌ام برای تجربه لوکس روزمره.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black"],
colorNames:["Black"],
colorNamesFa:["مشکی"],
sizes:["MM"],
sizesFa:["MM"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-22",
brand:"louis-vuitton",
name:"Coussin PM",
nameFa:"کوسن پی‌ام",
oldPrice:"$5,100",
newPrice:"$4,690",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton22.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton22.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=22",
description:"Premium Coussin PM crafted with luxurious Louis Vuitton details.",
descriptionFa:"کوسن پی‌ام باکیفیت با جزئیات لوکس لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["cream","black"],
colorNames:["Cream","Black"],
colorNamesFa:["کرم","مشکی"],
sizes:["PM"],
sizesFa:["PM"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-23",
brand:"louis-vuitton",
name:"Oxford",
nameFa:"آکسفورد",
oldPrice:"$3,290",
newPrice:"$2,990",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton23.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton23.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=23",
description:"Sophisticated Oxford handbag with premium Louis Vuitton craftsmanship.",
descriptionFa:"کیف شیک آکسفورد با ساخت باکیفیت لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["brown"],
colorNames:["Brown"],
colorNamesFa:["قهوه‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Leather",
materialFa:"چرم"
},
{
id:"louis-vuitton-24",
brand:"louis-vuitton",
name:"Grand Palais",
nameFa:"گرند پله",
oldPrice:"$3,990",
newPrice:"$3,590",
image:"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton24.jpg",
images:[
"../../../../../src/assets/images/acs-images/Louis Vuitton/Louis Vuitton24.jpg",
],
url:"../pdp/pdp.html?brand=louis-vuitton&id=24",
description:"Luxury Grand Palais handbag with timeless Louis Vuitton style.",
descriptionFa:"کیف لوکس گرند پله با سبک ماندگار لویی ویتون.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["black","brown"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Large"],
sizesFa:["بزرگ"],
material:"Leather",
materialFa:"چرم"
}
];