export const collection = {
brand:"Chanel",
brandFa:"شنل",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
description:"Discover elegant Chanel accessories designed to complement a refined and timeless style.",
descriptionFa:"اکسسوری‌های ظریف شنل برای تکمیل استایلی شیک و ماندگار."
};

export const products = [
{
id:"chanel-01",
name:"Coco Crush Bracelet",
nameFa:"کوکو کراش بریسلت",
oldPrice:"$8,200",
newPrice:"$7,790",
image:"../../../../../src/assets/images/acs-images/Chenal/bracelet1.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/bracelet1.jpg"],
description:"An elegant Coco Crush bracelet with a refined design inspired by Chanel's signature aesthetic.",
descriptionFa:"دستبند ظریف کوکو کراش با طراحی شیک و الهام‌گرفته از سبک خاص شنل.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-02",
name:"Camelia Bracelet",
nameFa:"کملیا بریسلت",
oldPrice:"$2,350",
newPrice:"$2,090",
image:"../../../../../src/assets/images/acs-images/Chenal/bracelet2.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/bracelet2.jpg"],
description:"A delicate Camelia bracelet featuring a graceful design inspired by the iconic Chanel flower.",
descriptionFa:"دستبند ظریف کملیا با طراحی لطیف و الهام‌گرفته از گل نمادین شنل.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-03",
name:"Ultra Bracelet",
nameFa:"اولترا بریسلت",
oldPrice:"$2,450",
newPrice:"$2,190",
image:"../../../../../src/assets/images/acs-images/Chenal/bracelet3.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/bracelet3.jpg"],
description:"A modern Ultra bracelet combining a clean silhouette with an elegant finish.",
descriptionFa:"دستبند مدرن اولترا با ظاهری ساده و پرداختی شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-04",
name:"Comete Bracelet",
nameFa:"کومت بریسلت",
oldPrice:"$2,180",
newPrice:"$1,950",
image:"../../../../../src/assets/images/acs-images/Chenal/bracelet4.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/bracelet4.jpg"],
description:"A sophisticated Comete bracelet with a delicate celestial-inspired appearance.",
descriptionFa:"دستبند ظریف کومت با ظاهری شیک و الهام‌گرفته از ستاره‌ها.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-05",
name:"Lion Necklace",
nameFa:"لایِن نکلس",
oldPrice:"$5,450",
newPrice:"$4,990",
image:"../../../../../src/assets/images/acs-images/Chenal/necklace1.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/necklace1.jpg"],
description:"A statement Lion necklace with a distinctive and sophisticated design.",
descriptionFa:"گردنبند چشمگیر لایِن با طراحی خاص و ظریف.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-06",
name:"Plume de Necklace",
nameFa:"پلوم دو نکلس",
oldPrice:"$3,250",
newPrice:"$2,990",
image:"../../../../../src/assets/images/acs-images/Chenal/necklace2.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/necklace2.jpg"],
description:"A graceful Plume de necklace inspired by the lightness of a feather.",
descriptionFa:"گردنبند ظریف پلوم دو با طراحی الهام‌گرفته از لطافت پر.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-07",
name:"Bouton de Camelia Necklace",
nameFa:"بوتون دو کملیا نکلس",
oldPrice:"$3,150",
newPrice:"$2,850",
image:"../../../../../src/assets/images/acs-images/Chenal/necklace3.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/necklace3.jpg"],
description:"A refined necklace inspired by the timeless Camelia motif.",
descriptionFa:"گردنبندی ظریف با الهام از نقش ماندگار کملیا.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-08",
name:"Ruban Necklace",
nameFa:"روبان نکلس",
oldPrice:"$3,450",
newPrice:"$3,090",
image:"../../../../../src/assets/images/acs-images/Chenal/necklace4.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/necklace4.jpg"],
description:"An elegant Ruban necklace featuring a graceful ribbon-inspired silhouette.",
descriptionFa:"گردنبند شیک روبان با طراحی ظریف و الهام‌گرفته از فرم روبان.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-09",
name:"My Dior Ring",
nameFa:"مای دیور رینگ",
oldPrice:"$2,790",
newPrice:"$2,490",
image:"../../../../../src/assets/images/acs-images/Chenal/ring1.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/ring1.jpg"],
description:"A refined statement ring with an elegant and contemporary appearance.",
descriptionFa:"انگشتری ظریف و چشمگیر با ظاهری مدرن و شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-10",
name:"Signature de Ring",
nameFa:"سیگنیچر دو رینگ",
oldPrice:"$2,950",
newPrice:"$2,690",
image:"../../../../../src/assets/images/acs-images/Chenal/ring2.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/ring2.jpg"],
description:"A sophisticated Signature de ring with a clean and timeless design.",
descriptionFa:"انگشتر شیک سیگنیچر دو با طراحی ساده و ماندگار.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-11",
name:"Etoile Filante Ring",
nameFa:"اِتوال فی‌لانت رینگ",
oldPrice:"$3,850",
newPrice:"$3,490",
image:"../../../../../src/assets/images/acs-images/Chenal/ring3.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/ring3.jpg"],
description:"An elegant Etoile Filante ring inspired by a delicate shooting star.",
descriptionFa:"انگشتری ظریف اِتوال فی‌لانت با الهام از زیبایی یک ستاره دنباله‌دار.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-12",
name:"Premiere Ring",
nameFa:"پریمیر رینگ",
oldPrice:"$4,150",
newPrice:"$3,790",
image:"../../../../../src/assets/images/acs-images/Chenal/ring4.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/ring4.jpg"],
description:"A refined Premiere ring with a sophisticated and elegant silhouette.",
descriptionFa:"انگشتری ظریف پریمیر با فرم شیک و چشم‌نواز.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-13",
name:"Butterfly Glasses",
nameFa:"باترفلای گلاسِز",
oldPrice:"$1,980",
newPrice:"$1,790",
image:"../../../../../src/assets/images/acs-images/Chenal/glasses1.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/glasses1.jpg"],
description:"Elegant butterfly-shaped glasses with a refined and feminine silhouette.",
descriptionFa:"عینک ظریف با فرم پروانه‌ای و ظاهری شیک و زنانه.",
scategory:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-14",
name:"Pilot Glasses",
nameFa:"پایلِت گلاسِز",
oldPrice:"$2,050",
newPrice:"$1,850",
image:"../../../../../src/assets/images/acs-images/Chenal/glasses2.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/glasses2.jpg"],
description:"Classic pilot glasses combining a confident shape with a refined finish.",
descriptionFa:"عینک پایلِت کلاسیک با فرم جذاب و ظاهری شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-15",
name:"Square Glasses",
nameFa:"اسکوئر گلاسِز",
oldPrice:"$1,850",
newPrice:"$1,650",
image:"../../../../../src/assets/images/acs-images/Chenal/glasses3.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/glasses3.jpg"],
description:"Modern square glasses with a clean and sophisticated silhouette.",
descriptionFa:"عینک مربعی مدرن با فرم ساده و ظاهری شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-16",
name:"Cat-Eye Glasses",
nameFa:"کَت‌آی گلاسِز",
oldPrice:"$2,390",
newPrice:"$2,090",
image:"../../../../../src/assets/images/acs-images/Chenal/glasses4.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/glasses4.jpg"],
description:"Feminine cat-eye glasses with an elegant and distinctive shape.",
descriptionFa:"عینک زنانه کَت‌آی با فرم خاص و ظاهری ظریف.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-17",
name:"Classic CC Belt",
nameFa:"کلاسیک سی‌سی بِلْت",
oldPrice:"$5,990",
newPrice:"$5,390",
image:"../../../../../src/assets/images/acs-images/Chenal/belt1.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/belt1.jpg"],
description:"A classic CC belt featuring an elegant signature-inspired design.",
descriptionFa:"کمربند کلاسیک سی‌سی با طراحی شیک و الهام‌گرفته از نشان نمادین.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-18",
name:"Chain Belt",
nameFa:"چِین بِلْت",
oldPrice:"$7,200",
newPrice:"$6,690",
image:"../../../../../src/assets/images/acs-images/Chenal/belt2.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/belt2.jpg"],
description:"A sophisticated chain belt designed to add an elegant accent to any look.",
descriptionFa:"کمربند زنجیری شیک که جلوه‌ای ظریف و متفاوت به استایل می‌دهد.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-19",
name:"Leather CC Belt",
nameFa:"لِذِر سی‌سی بِلْت",
oldPrice:"$2,250",
newPrice:"$1,990",
image:"../../../../../src/assets/images/acs-images/Chenal/belt3.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/belt3.jpg"],
description:"A refined leather CC belt combining a classic silhouette with an elegant finish.",
descriptionFa:"کمربند چرمی سی‌سی با فرم کلاسیک و پرداختی شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-20",
name:"Reversible Belt",
nameFa:"ریوِرسِبِل بِلْت",
oldPrice:"$4,250",
newPrice:"$3,890",
image:"../../../../../src/assets/images/acs-images/Chenal/belt4.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/belt4.jpg"],
description:"A versatile reversible belt offering two styling options in one elegant design.",
descriptionFa:"کمربند دوطرفه و کاربردی با امکان استفاده در دو استایل متفاوت.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-21",
name:"Tweed Headband",
nameFa:"توید هِدبَند",
oldPrice:"$3,850",
newPrice:"$3,450",
image:"../../../../../src/assets/images/acs-images/Chenal/headband1.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/headband1.jpg"],
description:"A sophisticated tweed headband adding a refined Chanel-inspired touch.",
descriptionFa:"هدبند تویدی شیک با جلوه‌ای ظریف و الهام‌گرفته از سبک شنل.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-22",
name:"CC Logo Headband",
nameFa:"سی‌سی لوگو هِدبَند",
oldPrice:"$5,100",
newPrice:"$4,690",
image:"../../../../../src/assets/images/acs-images/Chenal/headband2.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/headband2.jpg"],
description:"An elegant headband featuring a distinctive CC logo detail.",
descriptionFa:"هدبندی شیک با جزئیات متمایز لوگوی سی‌سی.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-23",
name:"Pearl Headband",
nameFa:"پِرل هِدبَند",
oldPrice:"$3,290",
newPrice:"$2,990",
image:"../../../../../src/assets/images/acs-images/Chenal/headband3.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/headband3.jpg"],
description:"A delicate pearl headband designed to add an elegant finishing touch.",
descriptionFa:"هدبند ظریف مرواریدی برای ایجاد جلوه‌ای شیک و کامل در استایل.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"chanel-24",
name:"Leather Headband",
nameFa:"لِذِر هِدبَند",
oldPrice:"$3,990",
newPrice:"$3,590",
image:"../../../../../src/assets/images/acs-images/Chenal/headband4.jpg",
images:["../../../../../src/assets/images/acs-images/Chenal/headband4.jpg"],
description:"A refined leather headband with a clean and sophisticated appearance.",
descriptionFa:"هدبند چرمی ظریف با ظاهری ساده و شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
}
];