export const collection = {
brand:"Gucci",
brandFa:"گوچی",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
description:"Discover the latest Gucci luxury accessories collection, featuring elegant designs for a refined style.",
descriptionFa:"جدیدترین کالکشن اکسسوری‌های لوکس گوچی را با طراحی‌های ظریف و شیک مشاهده کنید."
};
export const products = [
{
id:"gucci-01",
name:"Ring",
nameFa:"رینگ",
oldPrice:"$8,200",
newPrice:"$7,790",
image:"../../../../../src/assets/images/acs-images/Gucci/bracelete1.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/bracelete1.jpg"],
description:"An elegant Gucci ring with a refined design created to complement a sophisticated style.",
descriptionFa:"انگشتری ظریف از گوچی با طراحی شیک که برای تکمیل استایلی خاص و زیبا طراحی شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-02",
name:"Neverfull MM",
nameFa:"نِوِرفول ام‌ام",
oldPrice:"$2,350",
newPrice:"$2,090",
image:"../../../../../src/assets/images/acs-images/Gucci/bracelete2.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/bracelete2.jpg"],
description:"A refined Gucci Neverfull MM design combining an elegant appearance with everyday versatility.",
descriptionFa:"مدل ظریف نِوِرفول ام‌ام از گوچی با ظاهری شیک و کاربردی برای استفاده روزمره.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-03",
name:"Speedy Bandoulière 25",
nameFa:"اسپیدی باندولیر ۲۵",
oldPrice:"$2,450",
newPrice:"$2,190",
image:"../../../../../src/assets/images/acs-images/Gucci/bracelete3.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/bracelete3.jpg"],
description:"A compact Gucci Speedy Bandoulière 25 design with a timeless and elegant silhouette.",
descriptionFa:"مدل اسپیدی باندولیر ۲۵ از گوچی با فرم جمع‌وجور، ماندگار و شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-04",
name:"Alma BB",
nameFa:"آلما بی‌بی",
oldPrice:"$2,180",
newPrice:"$1,950",
image:"../../../../../src/assets/images/acs-images/Gucci/bracelete4.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/bracelete4.jpg"],
description:"A sophisticated Gucci Alma BB design with a graceful shape and elegant finish.",
descriptionFa:"مدل آلما بی‌بی از گوچی با فرمی ظریف و پرداختی شیک و چشم‌نواز.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-05",
name:"Twist MM",
nameFa:"توئیست ام‌ام",
oldPrice:"$5,450",
newPrice:"$4,990",
image:"../../../../../src/assets/images/acs-images/Gucci/necklace1.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/necklace1.jpg"],
description:"An elegant Gucci Twist MM design featuring a sophisticated and distinctive silhouette.",
descriptionFa:"مدل توئیست ام‌ام از گوچی با طراحی متمایز، ظریف و شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-06",
name:"Pochette Métis",
nameFa:"پوشت متیس",
oldPrice:"$3,250",
newPrice:"$2,990",
image:"../../../../../src/assets/images/acs-images/Gucci/necklace2.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/necklace2.jpg"],
description:"A refined Gucci Pochette Métis design combining a compact shape with an elegant appearance.",
descriptionFa:"مدل پوشت متیس از گوچی با فرم جمع‌وجور و ظاهری ظریف و شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-07",
name:"Loop Hobo",
nameFa:"لوپ هوبو",
oldPrice:"$3,150",
newPrice:"$2,850",
image:"../../../../../src/assets/images/acs-images/Gucci/necklace3.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/necklace3.jpg"],
description:"A graceful Gucci Loop Hobo design offering a relaxed yet sophisticated appearance.",
descriptionFa:"مدل لوپ هوبو از گوچی با ظاهری راحت، ظریف و در عین حال شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-08",
name:"CarryAll PM",
nameFa:"کری‌اُل پی‌ام",
oldPrice:"$3,450",
newPrice:"$3,090",
image:"../../../../../src/assets/images/acs-images/Gucci/necklace4.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/necklace4.jpg"],
description:"A versatile Gucci CarryAll PM design created for an elegant and practical everyday style.",
descriptionFa:"مدل کری‌اُل پی‌ام از گوچی با طراحی کاربردی برای یک استایل روزمره و شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-09",
name:"Boulogne",
nameFa:"بولون",
oldPrice:"$2,790",
newPrice:"$2,490",
image:"../../../../../src/assets/images/acs-images/Gucci/ring1.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/ring1.jpg"],
description:"An elegant Gucci Boulogne design with a refined silhouette suitable for sophisticated looks.",
descriptionFa:"مدل بولون از گوچی با فرمی ظریف و مناسب برای استایل‌های شیک و خاص.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-10",
name:"Diane",
nameFa:"دایان",
oldPrice:"$2,950",
newPrice:"$2,690",
image:"../../../../../src/assets/images/acs-images/Gucci/ring2.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/ring2.jpg"],
description:"A timeless Gucci Diane design combining an elegant shape with a sophisticated finish.",
descriptionFa:"مدل دایان از گوچی با طراحی ماندگار، فرم زیبا و ظاهری شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-11",
name:"OnTheGo MM",
nameFa:"آن‌دِگو ام‌ام",
oldPrice:"$3,850",
newPrice:"$3,490",
image:"../../../../../src/assets/images/acs-images/Gucci/ring3.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/ring3.jpg"],
description:"A spacious Gucci OnTheGo MM design combining practicality with an elegant appearance.",
descriptionFa:"مدل جادار آن‌دِگو ام‌ام از گوچی با ترکیبی از کاربردی بودن و ظاهری شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-12",
name:"Bella Tote",
nameFa:"بلا توت",
oldPrice:"$4,150",
newPrice:"$3,790",
image:"../../../../../src/assets/images/acs-images/Gucci/ring4.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/ring4.jpg"],
description:"A sophisticated Gucci Bella Tote design with an elegant and versatile silhouette.",
descriptionFa:"مدل بلا توت از گوچی با فرمی شیک، ظریف و کاربردی.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-13",
name:"Nano Speedy",
nameFa:"نانو اسپیدی",
oldPrice:"$1,980",
newPrice:"$1,790",
image:"../../../../../src/assets/images/acs-images/Gucci/glasses1.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/glasses1.jpg"],
description:"A compact Gucci Nano Speedy design with a delicate silhouette and refined appearance.",
descriptionFa:"مدل نانو اسپیدی از گوچی با فرم کوچک، ظریف و ظاهری شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-14",
name:"Wallet On Chain Ivy",
nameFa:"والت آن چین آیوی",
oldPrice:"$2,050",
newPrice:"$1,850",
image:"../../../../../src/assets/images/acs-images/Gucci/glasses2.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/glasses2.jpg"],
description:"A refined Gucci Wallet On Chain Ivy design combining compact functionality with elegant styling.",
descriptionFa:"مدل والت آن چین آیوی از گوچی با طراحی جمع‌وجور، کاربردی و شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-15",
name:"Félicie Pochette",
nameFa:"فِلیسی پوشت",
oldPrice:"$1,850",
newPrice:"$1,650",
image:"../../../../../src/assets/images/acs-images/Gucci/glasses3.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/glasses3.jpg"],
description:"A graceful Gucci Félicie Pochette design with a compact and elegant silhouette.",
descriptionFa:"مدل فِلیسی پوشت از گوچی با فرمی جمع‌وجور، ظریف و زیبا.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-16",
name:"Mini Bumbag",
nameFa:"مینی بام‌بگ",
oldPrice:"$2,390",
newPrice:"$2,090",
image:"../../../../../src/assets/images/acs-images/Gucci/glasses4.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/glasses4.jpg"],
description:"A compact Gucci Mini Bumbag design offering a modern and practical accessory option.",
descriptionFa:"مدل مینی بام‌بگ از گوچی با طراحی جمع‌وجور، مدرن و کاربردی.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"},
{
id:"gucci-17",
name:"Side Trunk MM",
nameFa:"ساید ترانک ام‌ام",
oldPrice:"$5,990",
newPrice:"$5,390",
image:"../../../../../src/assets/images/acs-images/Gucci/belt1.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/belt1.jpg"],
description:"A distinctive Gucci Side Trunk MM design combining a structured silhouette with elegant details.",
descriptionFa:"مدل ساید ترانک ام‌ام از گوچی با فرم ساختاریافته و جزئیات ظریف.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-18",
name:"GO-14 MM",
nameFa:"گو-۱۴ ام‌ام",
oldPrice:"$7,200",
newPrice:"$6,690",
image:"../../../../../src/assets/images/acs-images/Gucci/belt2.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/belt2.jpg"],
description:"A sophisticated Gucci GO-14 MM design featuring an elegant and contemporary silhouette.",
descriptionFa:"مدل گو-۱۴ ام‌ام از گوچی با فرم مدرن، ظریف و چشم‌نواز.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-19",
name:"Liv Pochette",
nameFa:"لیو پوشت",
oldPrice:"$2,250",
newPrice:"$1,990",
image:"../../../../../src/assets/images/acs-images/Gucci/belt3.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/belt3.jpg"],
description:"A refined Gucci Liv Pochette design with a compact silhouette and elegant appearance.",
descriptionFa:"مدل لیو پوشت از گوچی با فرم جمع‌وجور و ظاهری ظریف و شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-20",
name:"Dauphine MM",
nameFa:"دافین ام‌ام",
oldPrice:"$4,250",
newPrice:"$3,890",
image:"../../../../../src/assets/images/acs-images/Gucci/belt4.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/belt4.jpg"],
description:"A timeless Gucci Dauphine MM design combining elegant proportions with a refined finish.",
descriptionFa:"مدل دافین ام‌ام از گوچی با تناسبی زیبا و پرداختی شیک و ماندگار.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-21",
name:"Lockme Ever MM",
nameFa:"لاک‌می اِوِر ام‌ام",
oldPrice:"$3,850",
newPrice:"$3,450",
image:"../../../../../src/assets/images/acs-images/Gucci/headband1.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/headband1.jpg"],
description:"A refined Gucci Lockme Ever MM design with a sophisticated and versatile silhouette.",
descriptionFa:"مدل لاک‌می اِوِر ام‌ام از گوچی با طراحی ظریف، شیک و کاربردی.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-22",
name:"Coussin PM",
nameFa:"کوسَن پی‌ام",
oldPrice:"$5,100",
newPrice:"$4,690",
image:"../../../../../src/assets/images/acs-images/Gucci/headband2.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/headband2.jpg"],
description:"A soft and elegant Gucci Coussin PM design with a distinctive contemporary appearance.",
descriptionFa:"مدل نرم و ظریف کوسَن پی‌ام از گوچی با ظاهری مدرن و متمایز.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-23",
name:"Oxford",
nameFa:"آکسفورد",
oldPrice:"$3,290",
newPrice:"$2,990",
image:"../../../../../src/assets/images/acs-images/Gucci/headband3.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/headband3.jpg"],
description:"A sophisticated Gucci Oxford design with a classic silhouette and refined finish.",
descriptionFa:"مدل آکسفورد از گوچی با طراحی کلاسیک، ظریف و پرداختی شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
},
{
id:"gucci-24",
name:"Grand Palais",
nameFa:"گرند پَله",
oldPrice:"$3,990",
newPrice:"$3,590",
image:"../../../../../src/assets/images/acs-images/Gucci/headband4.jpg",
images:["../../../../../src/assets/images/acs-images/Gucci/headband4.jpg"],
description:"A refined Gucci Grand Palais design combining an elegant silhouette with timeless appeal.",
descriptionFa:"مدل گرند پَله از گوچی با فرمی ظریف و جذابیتی ماندگار.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["gold","silver"],
colorNames:["Gold","Silver"],
colorNamesFa:["طلایی","نقره‌ای"],
sizes:["Medium"],
sizesFa:["متوسط"],
material:"Gold",
materialFa:"طلا"
}
];