export const products = [
{
id:"prada-01",
name:"Ring",
nameFa:"رینگ",
oldPrice:"$8,200",
newPrice:"$7,790",
image:"../../../../../src/assets/images/acs-images/Prada/bracelet1.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/bracelet1.jpg"],
url:"#",
description:"Elegant bracelet crafted with premium materials.",
descriptionFa:"دستبندی ظریف که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"prada-02",
name:"Neverfull MM",
nameFa:"نِوِرفول ام‌ام",
oldPrice:"$2,350",
newPrice:"$2,090",
image:"../../../../../src/assets/images/acs-images/Prada/bracelet2.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/bracelet2.jpg"],
url:"#",
description:"Elegant luxury accessory crafted with premium materials.",
descriptionFa:"اکسسوری لوکس و ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"prada-03",
name:"Speedy Bandoulière 25",
nameFa:"اسپیدی باندولیر ۲۵",
oldPrice:"$2,450",
newPrice:"$2,190",
image:"../../../../../src/assets/images/acs-images/Prada/bracelet3.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/bracelet3.jpg"],
url:"#",
description:"Elegant luxury accessory designed with a refined finish.",
descriptionFa:"اکسسوری لوکس با طراحی ظریف و پرداختی زیبا.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"prada-04",
name:"Alma BB",
nameFa:"آلما بی‌بی",
oldPrice:"$2,180",
newPrice:"$1,950",
image:"../../../../../src/assets/images/acs-images/Prada/bracelet4.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/bracelet4.jpg"],
url:"#",
description:"Elegant luxury accessory with a timeless design.",
descriptionFa:"اکسسوری لوکس و ظریف با طراحی ماندگار.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"prada-05",
name:"Twist MM",
nameFa:"توئیست ام‌ام",
oldPrice:"$5,450",
newPrice:"$4,990",
image:"../../../../../src/assets/images/acs-images/Prada/necklace1.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/necklace1.jpg"],
url:"#",
description:"Elegant necklace crafted with premium materials.",
descriptionFa:"گردنبندی ظریف که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"prada-06",
name:"Pochette Métis",
nameFa:"پوشت متیس",
oldPrice:"$3,250",
newPrice:"$2,990",
image:"../../../../../src/assets/images/acs-images/Prada/necklace2.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/necklace2.jpg"],
url:"#",
description:"Elegant luxury accessory crafted with premium materials.",
descriptionFa:"اکسسوری لوکس و ظریفی که با استفاده از مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"prada-07",
name:"Loop Hobo",
nameFa:"لوپ هوبو",
oldPrice:"$3,150",
newPrice:"$2,850",
image:"../../../../../src/assets/images/acs-images/Prada/necklace3.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/necklace3.jpg"],
url:"#",
description:"Sophisticated luxury accessory with an elegant design.",
descriptionFa:"اکسسوری لوکس و شیک با طراحی زیبا.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"prada-08",
name:"CarryAll PM",
nameFa:"کری‌اُل پی‌ام",
oldPrice:"$3,450",
newPrice:"$3,090",
image:"../../../../../src/assets/images/acs-images/Prada/necklace4.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/necklace4.jpg"],
url:"#",
description:"Elegant luxury accessory with a refined appearance.",
descriptionFa:"اکسسوری لوکس و ظریف با ظاهری شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"prada-09",
name:"Boulogne",
nameFa:"بولون",
oldPrice:"$2,790",
newPrice:"$2,490",
image:"../../../../../src/assets/images/acs-images/Prada/ring1.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/ring1.jpg"],
url:"#",
description:"Elegant luxury accessory with a sophisticated finish.",
descriptionFa:"اکسسوری لوکس و ظریف با پرداختی شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"prada-10",
name:"Diane",
nameFa:"دایان",
oldPrice:"$2,950",
newPrice:"$2,690",
image:"../../../../../src/assets/images/acs-images/Prada/ring2.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/ring2.jpg"],
url:"#",
description:"Elegant luxury accessory with a timeless appearance.",
descriptionFa:"اکسسوری لوکس و ظریف با ظاهری ماندگار.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"prada-11",
name:"OnTheGo MM",
nameFa:"آن‌دِگو ام‌ام",
oldPrice:"$3,850",
newPrice:"$3,490",
image:"../../../../../src/assets/images/acs-images/Prada/ring3.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/ring3.jpg"],
url:"#",
description:"Modern luxury accessory crafted with premium materials.",
descriptionFa:"اکسسوری لوکس و مدرن که با مواد باکیفیت ساخته شده است.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Gold",
materialFa:"طلا"
},
{
id:"prada-12",
name:"Bella Tote",
nameFa:"بلا توت",
oldPrice:"$4,150",
newPrice:"$3,790",
image:"../../../../../src/assets/images/acs-images/Prada/ring4.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/ring4.jpg"],
url:"#",
description:"Elegant luxury accessory with a premium finish.",
descriptionFa:"اکسسوری لوکس و ظریف با پرداختی باکیفیت.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"prada-13",
name:"Nano Speedy",
nameFa:"نانو اسپیدی",
oldPrice:"$1,980",
newPrice:"$1,790",
image:"../../../../../src/assets/images/acs-images/Prada/glasses1.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/glasses1.jpg"],
url:"#",
description:"Elegant luxury accessory with a compact and refined design.",
descriptionFa:"اکسسوری لوکس و ظریف با طراحی جمع‌وجور و شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"prada-14",
name:"Wallet On Chain Ivy",
nameFa:"والت آن چین آیوی",
oldPrice:"$2,050",
newPrice:"$1,850",
image:"../../../../../src/assets/images/acs-images/Prada/glasses2.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/glasses2.jpg"],
url:"#",
description:"Elegant chain accessory with a sophisticated design.",
descriptionFa:"اکسسوری زنجیری ظریف با طراحی شیک.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"prada-15",
name:"Félicie Pochette",
nameFa:"فِلیسی پوشت",
oldPrice:"$1,850",
newPrice:"$1,650",
image:"../../../../../src/assets/images/acs-images/Prada/glasses3.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/glasses3.jpg"],
url:"#",
description:"Elegant luxury accessory with a refined finish.",
descriptionFa:"اکسسوری لوکس و ظریف با پرداختی زیبا.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
},
{
id:"prada-16",
name:"Mini Bumbag",
nameFa:"مینی بام‌بگ",
oldPrice:"$2,390",
newPrice:"$2,090",
image:"../../../../../src/assets/images/acs-images/Prada/glasses4.jpg",
images:["../../../../../src/assets/images/acs-images/Prada/glasses4.jpg"],
url:"#",
description:"Compact luxury accessory with a modern design.",
descriptionFa:"اکسسوری لوکس و جمع‌وجور با طراحی مدرن.",
category:"Women's Accessories",
categoryFa:"اکسسوری زنانه",
gender:"Women",
genderFa:"زنانه",
colors:["#222222","#8B6F61"],
colorNames:["Black","Brown"],
colorNamesFa:["مشکی","قهوه‌ای"],
sizes:["Small","Medium","Large"],
sizesFa:["کوچک","متوسط","بزرگ"],
material:"Leather",
materialFa:"چرم"
}
];